language: python
python:
    - "3.5"
    - "3.5-dev"
    - "nightly"
install: "pip install -r requirements.txt"
before_script: "pybabel compile -d pysistem/translations"
script: "python manage.py run tests"
