language: python
python:
    - "3.5"
    - "3.5-dev"
    - "nightly"
install: "pip install flask flask-babel flask-sqlalchemy flask-migrate msgpack-python transliterate humanize"
before_script: "pybabel compile -d pysistem/translations"
script: "python -m pysistem run tests"
