language: python
python:
    - "3.5"
    - "3.5-dev"
    - "nightly"
install: "pip install flask flask-babel flask-sqlalchemy sqlalchemy-migrate msgpack-python transliterate humanize"
script: "python -m pysistem tests:run"
