"""empty message

Revision ID: b8506fa1f21e
Revises: 7ad3026f5ea3
Create Date: 2016-06-24 17:54:10.353285

"""

# revision identifiers, used by Alembic.
revision = 'b8506fa1f21e'
down_revision = '7ad3026f5ea3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('auto_marks_applied', sa.Boolean(), nullable=True))
    op.drop_column('lesson_user_association', 'points')
    op.add_column('user', sa.Column('points', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'points')
    op.add_column('lesson_user_association', sa.Column('points', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('lesson', 'auto_marks_applied')
    ### end Alembic commands ###
