#!/bin/bash
if [ ! $UID -eq 0 ]; then
	echo "Run as root"
	exit 1
fi
HOME="/home/pysistem"
sudo -u pysistem -- "/usr/local/lib/pysistem/upgrade.sh" $@
echo "Updating services..."
(cd "/home/pysistem/env/pysistem/temporary/pysistem/vm" && tar -cf - *) | (cd /; tar --no-same-owner -xf -)
echo "Cleaning up..."
rm -rf "/home/pysistem/env/pysistem/temporary"
echo "Done"

